version: '3.9'
services:
  db:
    env_file:
      - ../.env.test
    build:
      context: ..
      dockerfile: docker/Dockerfile-init
    ports:
      - 5432:5432
    restart: always

  cache:
    image: redis:latest
    ports:
      - 6379:6379

  server:
    build:
      context: ..
      args:
        - ENV=.test
      dockerfile: docker/Dockerfile
    environment:
      HOST_ADDRESS: 'http://localhost:3001/administrator'
      REDIS_HOST: 'cache'
      DATABASE_HOST: 'db'
    ports:
      - '3000:3001'
    depends_on:
      - db
      - cache
    command: npm run start:prod
